version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: kabord
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
  app:
    image: yassine374/kabord-bard:latest
    container_name: laravel_app
    ports:
      - "8088:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=kabord
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
    volumes:
      - ./:/var/www/html

volumes:
  dbdata:
